### ISSUE TITLE
Objective JH-6: Improved Image Testing

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#46]
## Motivation

We switched to using upstream repo2docker-action for our image builds, and added basic tests so we can catch regressions before deploying changes to the image. However, these tests are run from within GitHub actions, so can not test things that are only available inside the hub environment - primarily data access to any of the buckets.

## Proposal

Instead of executing the tests inside GitHub actions directly, GitHub actions will execute the tests inside a server it automatically spawns inside the JupyterHub. The workflow remains the same with respect to tests, except tests can now test for data access as well.

## Owners
 - @yuvipanda  (2i2c)
 - @batpad  (Development Seed)
 - @sunu (Development Seed)

## Success criteria

 - [ ] Tests run on JupyterHub in a controlled fashion, and can test for data access issues.
 - [ ] Test failures are reported clearly in the GitHub actions UI
 - [x] Have image creation and testing workflow well documented

**Comment by yuvipanda** [comment]
I did some exploratory testing here, and the way I'd like us to proceed here is:

1. Convert our test infrastructure to use `mystmd`, and use its `--execute` (https://mystmd.org/guide/execute-notebooks) to test the notebooks, rather than `pytest-notebook`
2. Contribute a feature to `mystmd` to support running tests on remote machines (via the binder API, or via the JupyterHub API)

This allows us to get into contributing into an important new part of the jupyter ecosystem (myst).

Here's a small proof of concept for doing this with the binder API:


https://github.com/user-attachments/assets/76d45e79-5acd-4226-a493-b3f03fba88bf

(proof of concept quality code at https://github.com/jupyter-book/mystmd/compare/main...yuvipanda:mystmd:binder-client?expand=1).

I'm not sure if we should do this with the binder API or the jupyterhub API. To be determined!

**Comment by batpad** [comment]
Outlining some more details here based on conversation with @yuvipanda -

## Context and Rationale

Firstly, on the rationale behind switching to the `myst` CLI to run tests, away from `pytest-notebook`:

`pytest-notebook` is what repo2docker uses to run tests and is built around the use-case of testing that notebook outputs remain consistent across tests. This made it very easy for us to get going with tests, and worked well to get an initial notebook test going.

Currently, tests execute the test notebooks against a Jupyter kernel running in the same container. What we want to be able to do is:

 - Build and push the docker image
 - Pull the container image onto an actual jupyterhub instance and start a server
 - Execute our tests locally or in CI, with the notebook execution happening on the remote JupyterHub instance

This will allow to run our tests in a more real-world scenario, to test that the image updates work when deployed on the hub.

The way `pytest-notebook` executes the notebooks is talking directly to the Jupyter ZeroMQ backend using `nbclient`, which requires the Jupyter kernel to be running in the same container / environment as the tests.

The [Myst CLI](https://github.com/jupyter-book/mystmd/), on the other hand, [uses](https://github.com/jupyter-book/mystmd/blob/main/packages/myst-execute/src/execute.ts#L4) the [`jupyterlab/services`](https://github.com/jupyterlab/jupyterlab/blob/main/packages/services/src/kernel/kernel.ts) to speak to the Jupyter kernel, which does so by using the Jupyter Rest API and using a websocket connection to the Jupyter server. Since this uses the network to communicate the Jupyter backend, it becomes trivial to run it against a remote Jupyter backend, and can be done with setting environment variables that can be used to configure the backend URL the Myst CLI is using (TODO: find exact docs on this).

This does mean that we won't get the tooling to compare and match outputs out of the box, as we did with `pytest-notebook`. We'd likely need to restructure the test notebook a bit to use `assert` statements or so to do tests more explicitly, rather than the current "snapshot testing" approach. This should be relatively straightforward to do - there's likely some larger pros and cons between explicit `assert`-based testing and snapshot testing the outputs. I think long-term `assert` based testing might be easier to manage anyways, but for now would consider this change a practical response to our tooling change, and we can revisit if we want to do the work to move back to snapshot testing down the line.

## Tasks

So, what we need to do is:

 - [ ] Modify our test runner to use the `myst` CLI instead of `pytest-notebook`
 - [ ] Write a script that will:
    - Build and push the image to ECR / quay.io
    - Use the Jupyterhub API to pull the image on the staging cluster, and start a server
    - Poll for the server to have started, and once the server is started, grab the JUPYTERHUB_TOKEN
    - Set the Jupyterhub URL and token in the environment and run the Myst CLI to execute the test notebook(s)
    - If notebook throws an error, ensure errors are displayed nicely
 - [ ] Wire up the Github Actions flow to run this script as part of CI. We probably want to trigger the CI on the addition of a Label to PRs, to ensure it doesn't run for arbitrary external PRs.

@yuvipanda - please let me know if that all seems roughly right.

@jsignell would be great to get your eyes on this and surface any concerns or questions you might have around making this change to using the `myst` CLI instead of `pytest-notebook` to run our tests in order to be able to run them with execution happening on the actual hub.

cc @sunu

**Comment by yuvipanda** [comment]
Thanks for writing this down, @batpad!

https://mystmd.org/guide/execute-notebooks#manually-launch-a-jupyter-server is the docs on setting these env vars.

I think we need to decide on two approaches:

1. Using the JupyterHub (as you mentioned)
2. Or using binder.openveda.cloud instead.

(2) would be closer to what I prototyped in https://github.com/NASA-IMPACT/veda-jupyterhub/issues/46#issuecomment-2249380052. It has the following advantages:

1. We don't need to labels for access control, since the veda binder is open to the public
2. We don't have to deal with concurrent test runs, as we'd have to with the JupyterHub. We would have to use named servers to make sure multiple concurrent PRs don't clash with each other. With binder we can skip that
3. We won't have to push each PR to quay or ECR, as binderhub will automatically handle that. It also uses repo2docker so the build behavior wouldn't change.
4. This will be quicker to contribute upstream to mystmd, as there's already binder work there

The major con would be that the binder may have fewer permissions than the veda hubs, but I think that's a fine tradeoff to make for this PI.

So my recommendation is we do this with the binder API via binder.openveda.cloud rather than the JupyterHub API.

**Comment by yuvipanda** [comment]
Longer term, @agoose77 told me myst can do this kinda diffing (built in or externally) because it does build a DOM. But we don't need to do this right now.

Inorder to get this done by end of the quarter given capacities, my suggestion is that we:

1. Build this as a wrapper piece of code using the binderhub client API (similar to the POC linked to from https://github.com/NASA-IMPACT/veda-jupyterhub/issues/46#issuecomment-2249380052)
2. Dedicate time *next* PI to upstream this directly into mystmd.

This gives us time to make sure we can make the changes needed for the test notebook itself, given other time constraints.

**Comment by batpad** [comment]
We have not finished this yet. I wanted to make sure we updated to the latest `pangeo` upstream image with our current testing workflow before making major changes - this proved to take a little more time than expected due to issues we were finding with upstream. We finally managed to make the updates happen: https://github.com/2i2c-org/infrastructure/pull/4778

We also added comprehensive documentation for the current image management workflow: https://github.com/NASA-IMPACT/pangeo-notebook-veda-image/pull/29

There's a part of me that feels like we __finally__ have an easy-to-use stable mechanic to update and test our images, and I'm a bit wary to make changes to this process that's not broken. Updating and testing images involves folks from outside our team, and any changes we make will require a bunch of on-boarding to make folks comfortable with the process.

@brianmfreitag @yuvipanda - will be good to talk through this when we meet - I think we still have time this quarter to do these things if we want to - and I'm open to now that we have the Pangeo base updates done - but let's evaluate in terms of priorities.
